# Change these first
owner: exsules # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: oauth2
    url: https://accounts.exsules.dev/o/oauth2/certs

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.exsules.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Exsules Status
  introTitle: "Exsules Status Page"
  introMessage: "Exsules real-time status page."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
commitMessage:
  commitAuthorName: "exsules-bot"
  commitAuthorEmail: "16393509+exsules-bot@users.noreply.github.com"
  
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
